window.siteData = {
  regions: {
    all: "Tất cả miền",
    north: "Miền Bắc",
    central: "Miền Trung",
    south: "Miền Nam",
  },
  segments: {
    all: "Tất cả phân khúc",
    masteri: "Masteri Collection",
    lumiere: "LUMIÈRE Series",
    branded: "Branded Residences",
    township: "Đô thị tích hợp",
  },
  storeCategories: [
    { id: "all", label: "Tất cả", types: [] },
    { id: "drink", label: "Uống gì?", types: ["Ẩm thực"] },
    { id: "eat", label: "Ăn gì?", types: ["Ẩm thực"] },
    { id: "learn", label: "Học gì?", types: ["Gia đình", "Sức khỏe"] },
    { id: "go", label: "Đi gì?", types: ["Dịch vụ"] },
    { id: "work", label: "Làm gì?", types: ["Dịch vụ"] },
    { id: "play", label: "Chơi gì?", types: ["Gia đình"] },
    { id: "where", label: "Ở đâu?", types: ["Dịch vụ"] },
    { id: "shop", label: "Mua gì?", types: ["Mua sắm"] },
    { id: "place", label: "Địa điểm", types: ["Dịch vụ"] },
    { id: "online", label: "Shop Online", types: ["Mua sắm"] },
    { id: "stay", label: "Lưu trú", types: ["Dịch vụ"] },
  ],
  projects: [
    {
      id: "cosmo-central",
      name: "Masteri Cosmo Central",
      region: "south",
      segment: "masteri",
      city: "TP.HCM",
      location: "The Global City, TP.Thủ Đức",
      status: "Dự án mới nhất",
      image:
        "https://masterisehomes.com/_next/image?q=70&url=https%3A%2F%2Frevamp-ldp.masterisehomes.com%2Fuploads%2FMasteri_Cosmo_Central_bbf5e3661f.jpg&w=1200",
      description:
        "Dự án thuộc nhóm mới nhất của Masterise, gắn với hệ sinh thái The Global City và phù hợp để cập nhật cẩm nang cư dân tương lai, tiện ích, thương mại và thông báo vận hành.",
    },
    {
      id: "rivera-danang",
      name: "Masteri Rivera Danang",
      region: "central",
      segment: "masteri",
      city: "Đà Nẵng",
      location: "Đường Quy Mỹ, Hòa Cường Nam, Hải Châu",
      status: "Dự kiến bàn giao Q4/2026",
      image:
        "https://masterisehomes.com/masteri-rivera-danang/wp-content/uploads/2025/05/introduction-img.jpg",
      description:
        "Dự án đầu tiên của Masterise tại thị trường Đà Nẵng, cần nhóm thông tin giới thiệu, nhà mẫu, tiện ích và kênh hỗ trợ cư dân tương lai tại miền Trung.",
    },
    {
      id: "lumiere-midtown",
      name: "LUMIÈRE Midtown",
      region: "south",
      segment: "lumiere",
      city: "TP.HCM",
      location: "Đường Liên Phường, The Global City",
      status: "Dự kiến bàn giao 2027",
      image:
        "https://masterisehomes.com/lumiere-evergreen/wp-content/uploads/2023/12/image-6.jpg",
      description:
        "Dự án cao tầng thuộc The Global City, tập trung vào phong cách sống hiện đại, tiện ích riêng và thông tin dành cho cộng đồng cư dân tương lai.",
    },
    {
      id: "ocean-park-2",
      name: "Masteri Grand Coast",
      region: "north",
      segment: "masteri",
      city: "Hà Nội",
      location: "Ocean Park 2, Ocean City",
      status: "Đang triển khai",
      image:
        "https://masterisehomes.com/_next/image?q=70&url=https%3A%2F%2Frevamp-ldp.masterisehomes.com%2Fuploads%2FMasteri_Grand_Coast_a2c320e2ba.jpg&w=1200",
      description:
        "Cụm căn hộ Masteri Collection tại Ocean City, phù hợp để tổ chức cẩm nang theo tòa, tiện ích, gian hàng nội khu và lịch thông báo cư dân.",
    },
    {
      id: "ocean-park-3",
      name: "Masteri Era Landmark",
      region: "north",
      segment: "masteri",
      city: "Hưng Yên",
      location: "Ocean Park 3, Ocean City",
      status: "Đang triển khai",
      image:
        "https://masterisehomes.com/_next/image?q=70&url=https%3A%2F%2Frevamp-ldp.masterisehomes.com%2Fuploads%2FMasteri_Era_Landmark_66abef1c67.jpg&w=1200",
      description:
        "Dự án tại Ocean Park 3, cần cẩm nang tập trung vào kết nối tiện ích, hướng dẫn cư dân mới và nhịp sống cộng đồng trong đại đô thị.",
    },
    {
      id: "ocean-park-1",
      name: "Masteri Waterfront",
      region: "north",
      segment: "masteri",
      city: "Hà Nội",
      location: "Ocean Park, Gia Lâm",
      status: "Đã bàn giao từng phần",
      image:
        "https://masterisehomes.com/masteri-waterfront/wp-content/uploads/2023/10/1920x1080_EN-1-scaled.jpg",
      description:
        "Cộng đồng cư dân tại Ocean Park với nhu cầu tra cứu tin bàn giao, hướng dẫn sử dụng tiện ích và danh sách dịch vụ hằng ngày.",
    },
    {
      id: "west-heights",
      name: "Masteri West Heights",
      region: "north",
      segment: "masteri",
      city: "Hà Nội",
      location: "Smart City, Tây Mỗ - Đại Mỗ",
      status: "Đã bàn giao",
      image:
        "https://masterisehomes.com/masteri-west-heights/storage/app/uploads/public/60c/177/845/60c1778457718570366514.jpg",
      description:
        "Dự án tại lõi Smart City, phù hợp cho cẩm nang về tiện ích đa tầng, sảnh cư dân, hồ trung tâm và dịch vụ khu Tây Hà Nội.",
    },
    {
      id: "lumiere-evergreen",
      name: "LUMIÈRE Evergreen",
      region: "north",
      segment: "lumiere",
      city: "Hà Nội",
      location: "Smart City, Tây Mỗ - Đại Mỗ",
      status: "Đang triển khai",
      image: "https://masterisehomes.com/lumiere-evergreen/wp-content/uploads/2023/12/image-6.jpg",
      description:
        "Dự án LUMIÈRE tại Smart City, nên có trang tin về tiện ích wellness, thương mại dịch vụ và các mốc thông báo cư dân.",
    },
    {
      id: "global-city",
      name: "The Global City",
      region: "south",
      segment: "township",
      city: "TP.HCM",
      location: "Phường An Phú, TP.Thủ Đức",
      status: "Đang vận hành tiện ích",
      image:
        "https://masterisehomes.com/_next/image?q=70&url=https%3A%2F%2Frevamp-ldp.masterisehomes.com%2Fuploads%2FMasteri_Cosmo_Central_bbf5e3661f.jpg&w=1200",
      description:
        "Khu đô thị tích hợp với hệ sinh thái thương mại, giải trí và cư trú, phù hợp làm trung tâm điều hướng các dự án thành phần tại TP.HCM.",
    },
    {
      id: "grand-marina",
      name: "Grand Marina, Saigon",
      region: "south",
      segment: "branded",
      city: "TP.HCM",
      location: "Ba Son, Quận 1",
      status: "Đang vận hành từng phần",
      image:
        "https://masterisehomes.com/masteri-centre-point/storage/media/Zk8aNchsAUm2hlrJA42XywyE7nsVrvNclKSeB2qt.jpeg",
      description:
        "Dự án branded residences tại lõi trung tâm thành phố, cần nhóm thông tin cao cấp về dịch vụ cư dân, vận hành và tiện ích riêng.",
    },
    {
      id: "lumiere-riverside",
      name: "LUMIÈRE Riverside",
      region: "south",
      segment: "lumiere",
      city: "TP.HCM",
      location: "Xa lộ Hà Nội, TP.Thủ Đức",
      status: "Đã hình thành cộng đồng cư dân",
      image:
        "https://designbuild.vn/wp-content/uploads/2021/11/An-Phu-10-e1637912754563.jpg",
      description:
        "Cộng đồng LUMIÈRE tại khu Đông, phù hợp cập nhật dịch vụ nội khu, tiện ích gia đình và các thông báo vận hành theo tòa.",
    },
    {
      id: "an-phu",
      name: "Masteri An Phú",
      region: "south",
      segment: "masteri",
      city: "TP.HCM",
      location: "An Phú, TP.Thủ Đức",
      status: "Đã vận hành",
      image: "https://designbuild.vn/wp-content/uploads/2021/11/An-Phu-10-e1637912754563.jpg",
      description:
        "Dự án đã vận hành với cộng đồng cư dân ổn định, cần nhóm gian hàng dịch vụ, nhà thuốc, ăn uống và hỗ trợ sinh hoạt hằng ngày.",
    },
    {
      id: "centre-point",
      name: "Masteri Centre Point",
      region: "south",
      segment: "masteri",
      city: "TP.HCM",
      location: "Vinhomes Grand Park, TP.Thủ Đức",
      status: "Đã bàn giao từng phần",
      image:
        "https://masterisehomes.com/masteri-centre-point/storage/media/Zk8aNchsAUm2hlrJA42XywyE7nsVrvNclKSeB2qt.jpeg",
      description:
        "Dự án tại Vinhomes Grand Park, phù hợp tổ chức tin vận hành, tiện ích nội khu, dịch vụ cư dân và ưu đãi từ gian hàng.",
    },
  ],
  stores: [
    {
      projectId: "ocean-park-1",
      name: "Resident Market",
      type: "Mua sắm",
      floor: "Sảnh A",
      hours: "07:00 - 22:00",
      phone: "0988 458 783",
      note: "Nhu yếu phẩm, nước uống, đồ dùng căn hộ.",
    },
    {
      projectId: "ocean-park-1",
      name: "Waterfront Coffee",
      type: "Ẩm thực",
      floor: "Khối đế",
      hours: "06:30 - 21:30",
      phone: "0829 206 666",
      note: "Cafe, bánh ngọt, đồ uống mang đi.",
    },
    {
      projectId: "ocean-park-2",
      name: "Grand Coast Mart",
      type: "Mua sắm",
      floor: "Tầng 1",
      hours: "08:00 - 22:00",
      phone: "0902 158 159",
      note: "Gian hàng tiện ích cho cư dân mới nhận nhà.",
    },
    {
      projectId: "ocean-park-2",
      name: "Kids Aqua Club",
      type: "Gia đình",
      floor: "Khu tiện ích",
      hours: "09:00 - 18:00",
      phone: "0911 920 666",
      note: "Lớp bơi, hoạt động hè, dịch vụ cho trẻ em.",
    },
    {
      projectId: "ocean-park-3",
      name: "Era Food Corner",
      type: "Ẩm thực",
      floor: "Sảnh chính",
      hours: "10:00 - 21:00",
      phone: "0936 888 345",
      note: "Đồ ăn nhanh, cơm văn phòng, đặt món theo nhóm.",
    },
    {
      projectId: "west-heights",
      name: "West Heights Mini Mart",
      type: "Mua sắm",
      floor: "Sảnh S1",
      hours: "07:00 - 22:00",
      phone: "0966 220 118",
      note: "Đồ dùng hằng ngày, thực phẩm nhanh và dịch vụ giao tận sảnh.",
    },
    {
      projectId: "lumiere-evergreen",
      name: "Evergreen Wellness Desk",
      type: "Sức khỏe",
      floor: "Khu tiện ích",
      hours: "08:00 - 20:00",
      phone: "0904 778 899",
      note: "Tư vấn lịch tiện ích, lớp wellness và dịch vụ cộng đồng cư dân.",
    },
    {
      projectId: "rivera-danang",
      name: "Rivera Concierge",
      type: "Dịch vụ",
      floor: "Khu lễ tân",
      hours: "08:00 - 18:00",
      phone: "0888 456 789",
      note: "Thông tin dự án, đăng ký xem nhà mẫu, hỗ trợ cư dân tương lai.",
    },
    {
      projectId: "an-phu",
      name: "Thảo Điền Pharmacy",
      type: "Sức khỏe",
      floor: "Khối đế",
      hours: "07:30 - 22:00",
      phone: "028 7300 1122",
      note: "Nhà thuốc, vật tư y tế, tư vấn sức khỏe cơ bản.",
    },
    {
      projectId: "centre-point",
      name: "Centre Point Homecare",
      type: "Gia đình",
      floor: "Tầng 1",
      hours: "08:00 - 19:00",
      phone: "0908 567 111",
      note: "Vệ sinh căn hộ, sửa chữa nhỏ, chăm sóc nhà cửa.",
    },
    {
      projectId: "cosmo-central",
      name: "Cosmo Service Desk",
      type: "Dịch vụ",
      floor: "Sảnh thương mại",
      hours: "08:00 - 20:00",
      phone: "0988 458 783",
      note: "Tư vấn thông tin dự án, lịch tiện ích và kênh hỗ trợ cư dân tương lai.",
    },
    {
      projectId: "global-city",
      name: "Global City Concierge",
      type: "Dịch vụ",
      floor: "Khu trung tâm",
      hours: "09:00 - 21:00",
      phone: "0829 206 666",
      note: "Thông tin sự kiện, thương mại và tiện ích trong khu đô thị.",
    },
    {
      projectId: "lumiere-midtown",
      name: "Midtown Lifestyle Desk",
      type: "Dịch vụ",
      floor: "Khu thương mại",
      hours: "09:00 - 20:00",
      phone: "0911 920 666",
      note: "Cập nhật thông tin tiện ích, thương mại và hỗ trợ cư dân tương lai.",
    },
    {
      projectId: "grand-marina",
      name: "Marina Resident Lounge",
      type: "Dịch vụ",
      floor: "Sảnh cư dân",
      hours: "08:00 - 21:00",
      phone: "0908 567 111",
      note: "Hỗ trợ cư dân, thông tin tiện ích và dịch vụ cao cấp trong tòa nhà.",
    },
    {
      projectId: "lumiere-riverside",
      name: "Riverside Family Hub",
      type: "Gia đình",
      floor: "Khối đế",
      hours: "08:00 - 20:00",
      phone: "0933 889 900",
      note: "Dịch vụ gia đình, tiện ích sinh hoạt và các ưu đãi nội khu.",
    },
  ],
  projectNews: [
    {
      projectId: "cosmo-central",
      title: "Masteri Cosmo Central cập nhật khu tiện ích mới",
      summary: "Thông tin tổng quan về tiện ích, thương mại và kết nối trong The Global City.",
      tag: "Dự án",
      date: "11/06/2026",
      image:
        "https://masterisehomes.com/_next/image?q=70&url=https%3A%2F%2Frevamp-ldp.masterisehomes.com%2Fuploads%2FMasteri_Cosmo_Central_bbf5e3661f.jpg&w=960",
    },
    {
      projectId: "ocean-park-2",
      title: "Thông tin giá và chính sách dự án Masteri Grand Coast",
      summary: "Cập nhật nhóm thông tin bán hàng, ưu đãi và chính sách mới.",
      tag: "Chính sách",
      date: "11/06/2026",
      image:
        "https://masterisehomes.com/_next/image?q=70&url=https%3A%2F%2Frevamp-ldp.masterisehomes.com%2Fuploads%2FMasteri_Grand_Coast_a2c320e2ba.jpg&w=640",
    },
    {
      projectId: "west-heights",
      title: "Cư dân nhí Masteri West Heights học kỹ năng sơ cứu",
      summary: "Hoạt động cộng đồng dành cho gia đình và trẻ em trong khu đô thị.",
      tag: "Cộng đồng",
      date: "09/06/2026",
      image:
        "https://masterisehomes.com/masteri-west-heights/storage/app/uploads/public/60c/177/845/60c1778457718570366514.jpg",
    },
    {
      projectId: "lumiere-evergreen",
      title: "LUMIÈRE Evergreen gợi ý trải nghiệm wellness",
      summary: "Các hoạt động sống xanh, vận động và kết nối cộng đồng dành cho cư dân tương lai.",
      tag: "Wellness",
      date: "07/06/2026",
      image: "https://masterisehomes.com/lumiere-evergreen/wp-content/uploads/2023/12/image-6.jpg",
    },
    {
      projectId: "rivera-danang",
      title: "Masteri Rivera Danang cập nhật nhà mẫu",
      summary: "Tin tức mới cho cư dân tương lai tại Đà Nẵng.",
      tag: "Dự án",
      date: "03/06/2026",
      image:
        "https://masterisehomes.com/masteri-rivera-danang/wp-content/uploads/2025/05/introduction-img.jpg",
    },
    {
      projectId: "centre-point",
      title: "Masteri Centre Point hoàn thiện tiện ích nội khu",
      summary: "Tổng hợp thông tin vận hành, tiện ích và dịch vụ cư dân.",
      tag: "Vận hành",
      date: "01/06/2026",
      image:
        "https://masterisehomes.com/masteri-centre-point/storage/media/Zk8aNchsAUm2hlrJA42XywyE7nsVrvNclKSeB2qt.jpeg",
    },
    {
      projectId: "lumiere-midtown",
      title: "LUMIÈRE Midtown cập nhật tiện ích cư dân tương lai",
      summary: "Thông tin mới về khối đế thương mại, tiện ích riêng và kết nối tại The Global City.",
      tag: "Tiện ích",
      date: "30/05/2026",
      image: "https://masterisehomes.com/lumiere-evergreen/wp-content/uploads/2023/12/image-6.jpg",
    },
    {
      projectId: "ocean-park-1",
      title: "Nghệ thuật sống wellness tại Masteri Waterfront",
      summary: "Gợi ý lịch tiện ích, thể thao và chăm sóc sức khỏe cho cư dân.",
      tag: "Tiện ích",
      date: "28/05/2026",
      image:
        "https://masterisehomes.com/masteri-waterfront/wp-content/uploads/2023/10/1920x1080_EN-1-scaled.jpg",
    },
    {
      projectId: "ocean-park-3",
      title: "Không gian vui chơi mới cho cư dân nhí",
      summary: "Các hoạt động cuối tuần dành cho gia đình tại khu Ocean Park.",
      tag: "Gia đình",
      date: "26/05/2026",
      image:
        "https://masterisehomes.com/_next/image?q=70&url=https%3A%2F%2Frevamp-ldp.masterisehomes.com%2Fuploads%2FMasteri_Era_Landmark_66abef1c67.jpg&w=640",
    },
    {
      projectId: "global-city",
      title: "The Global City cập nhật lịch sự kiện cuối tuần",
      summary: "Tổng hợp hoạt động thương mại, giải trí và trải nghiệm cộng đồng trong khu đô thị.",
      tag: "Sự kiện",
      date: "24/05/2026",
      image:
        "https://masterisehomes.com/_next/image?q=70&url=https%3A%2F%2Frevamp-ldp.masterisehomes.com%2Fuploads%2FMasteri_Cosmo_Central_bbf5e3661f.jpg&w=960",
    },
    {
      projectId: "grand-marina",
      title: "Grand Marina, Saigon cập nhật dịch vụ cư dân",
      summary: "Các nhóm dịch vụ và lưu ý vận hành dành cho cư dân branded residences.",
      tag: "Vận hành",
      date: "22/05/2026",
      image:
        "https://masterisehomes.com/masteri-centre-point/storage/media/Zk8aNchsAUm2hlrJA42XywyE7nsVrvNclKSeB2qt.jpeg",
    },
    {
      projectId: "lumiere-riverside",
      title: "LUMIÈRE Riverside tổng hợp tiện ích gia đình",
      summary: "Gợi ý dịch vụ nội khu, tiện ích sinh hoạt và hoạt động cộng đồng cư dân.",
      tag: "Cộng đồng",
      date: "20/05/2026",
      image:
        "https://designbuild.vn/wp-content/uploads/2021/11/An-Phu-10-e1637912754563.jpg",
    },
    {
      projectId: "an-phu",
      title: "Masteri An Phú cập nhật nhóm dịch vụ hằng ngày",
      summary: "Danh sách tiện ích, nhà thuốc, ăn uống và hỗ trợ sinh hoạt quanh khối đế.",
      tag: "Dịch vụ",
      date: "18/05/2026",
      image: "https://designbuild.vn/wp-content/uploads/2021/11/An-Phu-10-e1637912754563.jpg",
    },
  ],
};
